#emailservice deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: emailservice
  name: emailservice
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
        - image: 639962416620.dkr.ecr.eu-west-2.amazonaws.com/arch-email-service-repository:latest
          name: emailservice
          ports:
            - containerPort: 5000
              name: emailservice
          env:
          - name: PORT
            value: "8080"

---
#emailservice service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: emailservice
  name: emailservice
spec:
  type: ClusterIP
  ports:
  - name: "emailservice"
    port: 8080
    targetPort: 5000
  selector:
    app: emailservice