#cartservice deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cartservice
  name: cartservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - image: 639962416620.dkr.ecr.eu-west-2.amazonaws.com/arch-cart-service-repository
          name: cartservice
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 7070
              name: cartservice

---
#cartservice service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cartservice
  name: cartservice
spec:
  type: ClusterIP
  ports:
  - name: "cartservice"
    port: 7070
    targetPort: 7070
  selector:
    app: cartservice