#loadgenerator deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loadgenerator
  name: loadgenerator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - image: 639962416620.dkr.ecr.eu-west-2.amazonaws.com/arch-loadgenerator:latest
          name: "loadgenerator"
          env:
          - name: FRONTEND_ADDR
            value: "frontend:80"
